//! The Rust printer: the erased tree as Rust source. Trusted, together with
//! the Rust toolchain beneath it.
//!
//! The erased tree already has the shape of the source, so this is mostly a
//! matter of spelling. Layout is left to rustfmt. Two constructs have no
//! direct Rust form and are printed through mutable state:
//!
//! ~~~text
//! loop (acc: u8 = 0) -> R { ... continue(next) ... break value ... }
//!
//! {
//!     let mut state_acc: u8 = 0;
//!     loop {
//!         let acc = state_acc;
//!         ... { state_acc = next; continue; } ... break value ...
//!     }
//! }
//! ~~~
//!
//! The state lives in variables of its own and each iteration rebinds the
//! source's names from them, so a `let` in the body that shadows a state
//! name cannot disturb the loop, exactly as in Locus. A `for` is printed the
//! same way around a Rust `for`, and yields its final state.
//!
//! Every value in the core is immutable and freely reusable, so structs and
//! enums derive `Copy`.
//!
//! A panic is printed as `panic!("{}", "message")`. The message is an
//! argument and never the format string, so its braces mean nothing to
//! `panic!`, and it is written as Rust's `{:?}` writes a string, which is a
//! string literal for any text. Whatever follows a panic in evaluation order
//! is still printed, as it is for a trap: the rest of a block, the other
//! arguments of a call, the call itself. Rust warns that such code is
//! unreachable, and the header allows exactly that on purpose, since the
//! printer keeps the shape of the source and does not prune it.
//!
//! A `let` whose value contains a panic, a trap, or a transfer of control
//! is printed with the type of its pattern, `let x: u8 = panic!(...)`,
//! because Rust may have nothing else to infer the type of `x` from, and
//! what follows may need it (E0282). Any other `let` is printed as the
//! source wrote it.
//!
//! `let mut` and assignment are printed as written, `x = e;` and
//! `x.f.0 = e;`, and `mut` only on a binding the function assigns to,
//! which is what Rust's `unused_mut` demands. Rust also warns of a value
//! that is assigned and never read, `unused_assignments`; the printer keeps
//! the shape of the source and does not prune dead stores, so the header
//! allows that lint as it allows unreachable code.
//!
//! Every integer literal is printed with its type as a suffix, `200_u8`,
//! `-5_i32`, so that Rust never has to infer the type of a literal from its
//! context and a literal standing alone, as the receiver of a method or as
//! a whole `let`, has one (E0689). A negative literal is parenthesized, so
//! that `(-5_i32).wrapping_add(1)` is the call on the literal and not on
//! `5_i32`. A cast is parenthesized too, `(a as u8) < b`, which is what
//! rustc asks for where a comparison follows an `as`.

use std::fmt::Write;

use crate::kernel::{MachineInt, Prim, VarId};
use crate::typed::CompareOp;

use super::interp::Value;
use super::tree::{EBlock, EExpr, EPattern, EStmt, EType, Module};

const HEADER: &str = "\
// Generated by Locus. Do not edit.
#![allow(dead_code, unused_variables, unused_parens, unused_braces, unreachable_code, unused_comparisons, unused_assignments)]
#![allow(clippy::all)]

/// The erasure of a proof. It occupies no space.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Proved;

/// The erasure of any other ghost value. It occupies no space.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Ghost;
";

/// The state variables of the loops enclosing the current position.
type Loops = Vec<Vec<String>>;

struct Printer<'m> {
    module: &'m Module,
    out: String,
    loops: Loops,
}

/// The module as Rust source.
pub fn print_module(module: &Module) -> String {
    let mut printer = Printer {
        module,
        out: String::from(HEADER),
        loops: Vec::new(),
    };
    for item in &module.structs {
        let _ = writeln!(
            printer.out,
            "\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub struct {} {{",
            item.name
        );
        for (name, ty) in &item.fields {
            let ty = printer.ty(ty);
            let _ = writeln!(printer.out, "    pub {name}: {ty},");
        }
        printer.out.push_str("}\n");
    }
    for item in &module.enums {
        let _ = writeln!(
            printer.out,
            "\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub enum {} {{",
            item.name
        );
        for variant in &item.variants {
            let payload: Vec<String> = variant.payload.iter().map(|ty| printer.ty(ty)).collect();
            if let Some(fields) = &variant.fields {
                let fields: Vec<String> = fields
                    .iter()
                    .zip(&payload)
                    .map(|(name, ty)| format!("{name}: {ty}"))
                    .collect();
                let _ = writeln!(
                    printer.out,
                    "    {} {{ {} }},",
                    variant.name,
                    fields.join(", ")
                );
            } else if payload.is_empty() {
                let _ = writeln!(printer.out, "    {},", variant.name);
            } else {
                let _ = writeln!(printer.out, "    {}({}),", variant.name, payload.join(", "));
            }
        }
        printer.out.push_str("}\n");
    }
    for function in &module.fns {
        let result = printer.ty(&function.result);
        // A constant is a `const` item: its body is one expression, which
        // Rust computes at compile time (the elaborator saw that it can).
        if function.constant
            && function.params.is_empty()
            && function.body.stmts.is_empty()
            && let Some(value) = &function.body.tail
        {
            let value = printer.expr(value);
            let _ = writeln!(
                printer.out,
                "\npub const {}: {result} = {value};",
                function.name
            );
            continue;
        }
        let params: Vec<String> = function
            .params
            .iter()
            .map(|(_, name, ty)| format!("{name}: {}", printer.ty(ty)))
            .collect();
        let _ = write!(
            printer.out,
            "\npub fn {}({}) -> {result} ",
            function.name,
            params.join(", ")
        );
        printer.loops.clear();
        let body = printer.block(&function.body);
        printer.out.push_str(&body);
        printer.out.push('\n');
    }
    indent(&printer.out)
}

/// Indents by brace depth. The printer emits one statement per line, and a
/// string literal, which is the message of a panic or of a trap, stays on
/// its line, so counting the braces outside literals is exact.
fn indent(source: &str) -> String {
    let mut out = String::new();
    let mut depth = 0usize;
    for line in source.lines() {
        let line = line.trim();
        let closes_first = line.starts_with('}');
        if closes_first {
            depth = depth.saturating_sub(1);
        }
        if !line.is_empty() {
            out.push_str(&"    ".repeat(depth));
            out.push_str(line);
        }
        out.push('\n');
        let (opens, closes) = braces(line);
        depth = (depth + opens).saturating_sub(closes - usize::from(closes_first));
    }
    out
}

/// The opening and closing braces of a line, outside its string literals.
fn braces(line: &str) -> (usize, usize) {
    let (mut opens, mut closes) = (0, 0);
    let mut in_literal = false;
    let mut chars = line.chars();
    while let Some(c) = chars.next() {
        match c {
            '\\' if in_literal => {
                chars.next();
            }
            '"' => in_literal = !in_literal,
            '{' if !in_literal => opens += 1,
            '}' if !in_literal => closes += 1,
            _ => {}
        }
    }
    (opens, closes)
}

fn tuple_of(items: &[String]) -> String {
    match items {
        [only] => format!("({only},)"),
        _ => format!("({})", items.join(", ")),
    }
}

impl Printer<'_> {
    fn ty(&self, ty: &EType) -> String {
        match ty {
            EType::Bool => "bool".into(),
            EType::Int(ty) => ty.name().into(),
            EType::Proved => "Proved".into(),
            EType::Ghost => "Ghost".into(),
            EType::Tuple(fields) => {
                let fields: Vec<String> = fields.iter().map(|field| self.ty(field)).collect();
                tuple_of(&fields)
            }
            EType::Struct(id) => self
                .module
                .structs
                .iter()
                .find(|item| item.id == *id)
                .map_or_else(|| "UnknownStruct".into(), |item| item.name.clone()),
            EType::Enum(id) => self
                .module
                .enums
                .iter()
                .find(|item| item.id == *id)
                .map_or_else(|| "UnknownEnum".into(), |item| item.name.clone()),
            EType::Fn(params, result) => {
                let params: Vec<String> = params.iter().map(|param| self.ty(param)).collect();
                format!("fn({}) -> {}", params.join(", "), self.ty(result))
            }
        }
    }

    fn block(&mut self, block: &EBlock) -> String {
        format!("{{\n{}}}", self.contents(block))
    }

    /// A block's statements and tail, without its braces. A loop, a `for`, a
    /// nested block, or a `continue` in tail position is written straight
    /// into the enclosing block instead of getting braces of its own.
    fn contents(&mut self, block: &EBlock) -> String {
        let mut out = String::new();
        for stmt in &block.stmts {
            match stmt {
                EStmt::Let { pattern, value } => {
                    let annotation =
                        if contains_divergence(value) && !matches!(pattern, EPattern::Wildcard) {
                            format!(": {}", self.pattern_type(pattern, diverges(value)))
                        } else {
                            String::new()
                        };
                    let value = self.expr(value);
                    let _ = writeln!(out, "let {}{annotation} = {value};", pattern_of(pattern));
                }
                EStmt::Assign { place, value } => {
                    let value = self.expr(value);
                    let mut target = place.name.clone();
                    for (index, name) in &place.path {
                        match name {
                            Some(name) => target.push_str(&format!(".{name}")),
                            None => target.push_str(&format!(".{index}")),
                        }
                    }
                    let _ = writeln!(out, "{target} = {value};");
                }
                EStmt::Expr(expr) => {
                    let expr = self.standing_alone(expr);
                    let _ = writeln!(out, "{expr};");
                }
            }
        }
        match block.tail.as_deref() {
            None => {}
            Some(EExpr::Block(inner)) => out.push_str(&self.contents(inner)),
            Some(EExpr::Loop { state, body, .. }) => out.push_str(&self.looping(state, body, None)),
            Some(EExpr::For {
                index,
                lo,
                hi,
                state,
                body,
            }) => {
                let header = format!("for {} in {}..{}", index.1, self.expr(lo), self.expr(hi));
                out.push_str(&self.looping(state, body, Some(header)));
            }
            Some(EExpr::Continue(next)) => out.push_str(&self.continuing(next)),
            Some(tail) => {
                out.push_str(&self.standing_alone(tail));
                out.push('\n');
            }
        }
        out
    }

    /// An expression that is a whole statement or a whole tail, where a
    /// `return` needs no parentheses.
    fn standing_alone(&mut self, expr: &EExpr) -> String {
        match expr {
            EExpr::Return(value) => format!("return {}", self.expr(value)),
            other => self.expr(other),
        }
    }

    /// The type of a pattern, for an annotation. A wildcard has no type of
    /// its own. Its part is left to Rust to infer, unless the value has the
    /// type `!` (`diverges`), when there is nothing to infer it from and any
    /// type will do, since no value ever reaches the pattern: it is `()`.
    fn pattern_type(&self, pattern: &EPattern, diverges: bool) -> String {
        match pattern {
            EPattern::Bind { ty, .. } => self.ty(ty),
            EPattern::Wildcard if diverges => "()".into(),
            EPattern::Wildcard => "_".into(),
            EPattern::Tuple(patterns) => {
                let types: Vec<String> = patterns
                    .iter()
                    .map(|pattern| self.pattern_type(pattern, diverges))
                    .collect();
                tuple_of(&types)
            }
        }
    }

    /// A loop or a `for` as statements: the state's declarations, the loop,
    /// and for a `for` the final state as the value.
    fn looping(
        &mut self,
        state: &[(VarId, String, EType, EExpr)],
        body: &EBlock,
        for_header: Option<String>,
    ) -> String {
        let (names, declare, rebind) = self.state(state);
        let result = tuple_of(&names);
        self.loops.push(names);
        let body = self.contents(body);
        self.loops.pop();
        match for_header {
            None => format!("{declare}loop {{\n{rebind}{body}}}\n"),
            Some(header) => format!("{declare}{header} {{\n{rebind}{body}}}\n{result}\n"),
        }
    }

    /// `continue(next...)` as statements. The right side is evaluated in
    /// full before any state is assigned.
    fn continuing(&mut self, next: &[EExpr]) -> String {
        let next = self.all(next);
        let slots = self.loops.last().cloned().unwrap_or_default();
        match slots.as_slice() {
            [] => "continue\n".into(),
            [slot] => format!("{slot} = {};\ncontinue\n", next.join(", ")),
            _ => format!("{} = {};\ncontinue\n", tuple_of(&slots), tuple_of(&next)),
        }
    }

    /// A condition, without the parentheses a comparison gets elsewhere.
    fn condition(&mut self, expr: &EExpr) -> String {
        let printed = self.expr(expr);
        match expr {
            EExpr::Compare { .. } => printed[1..printed.len() - 1].to_string(),
            _ => printed,
        }
    }

    fn all(&mut self, exprs: &[EExpr]) -> Vec<String> {
        exprs.iter().map(|expr| self.expr(expr)).collect()
    }

    /// Declares the state variables of a loop and returns their names, the
    /// declarations, and the rebinding of the source's names that starts
    /// each iteration.
    fn state(&mut self, state: &[(VarId, String, EType, EExpr)]) -> (Vec<String>, String, String) {
        let mut names = Vec::new();
        let mut declare = String::new();
        let mut rebind = String::new();
        for (_, name, ty, init) in state {
            let slot = format!("state_{name}");
            let init = self.expr(init);
            let _ = writeln!(declare, "let mut {slot}: {} = {init};", self.ty(ty));
            let _ = writeln!(rebind, "let {name} = {slot};");
            names.push(slot);
        }
        (names, declare, rebind)
    }

    fn expr(&mut self, expr: &EExpr) -> String {
        match expr {
            EExpr::Var { name, .. } => name.clone(),
            EExpr::Bool(value) => value.to_string(),
            EExpr::Literal(ty, value) => literal(*ty, *value),
            EExpr::Proved => "Proved".into(),
            EExpr::Ghost => "Ghost".into(),
            EExpr::Trap => "unreachable!(\"shown never to be reached\")".into(),
            EExpr::Panic { message } => format!("panic!(\"{{}}\", {message:?})"),
            EExpr::Tuple(fields) => tuple_of(&self.all(fields)),
            EExpr::Struct { name, fields, .. } => {
                let fields: Vec<String> = fields
                    .iter()
                    .map(|(field, value)| format!("{field}: {}", self.expr(value)))
                    .collect();
                format!("{name} {{ {} }}", fields.join(", "))
            }
            EExpr::Variant {
                enum_name,
                variant_name,
                payload,
                ..
            } => {
                let name = format!("{enum_name}::{variant_name}");
                let fields = self.module.variant_fields(enum_name, variant_name);
                let payload = self.all(payload);
                match fields {
                    // `V { a, b: y }`: a field given its own name is written once.
                    Some(fields) => {
                        let fields: Vec<String> = fields
                            .iter()
                            .zip(payload)
                            .map(|(field, value)| {
                                if *field == value {
                                    value
                                } else {
                                    format!("{field}: {value}")
                                }
                            })
                            .collect();
                        format!("{name} {{ {} }}", fields.join(", "))
                    }
                    None => variant_of(&name, None, &payload),
                }
            }
            EExpr::Field {
                target,
                index,
                name,
            } => {
                let target = self.expr(target);
                match name {
                    Some(name) => format!("{target}.{name}"),
                    None => format!("{target}.{index}"),
                }
            }
            EExpr::Method {
                prim,
                receiver,
                arguments,
            } => {
                let method = match prim {
                    Prim::Op(op, _) => op.name(),
                    other => other.name(),
                };
                format!(
                    "{}.{method}({})",
                    self.expr(receiver),
                    self.all(arguments).join(", ")
                )
            }
            EExpr::Compare { op, left, right } => {
                let op = match op {
                    CompareOp::Eq => "==",
                    CompareOp::Ne => "!=",
                    CompareOp::Lt => "<",
                    CompareOp::Le => "<=",
                    CompareOp::Gt => ">",
                    CompareOp::Ge => ">=",
                };
                format!("({} {op} {})", self.expr(left), self.expr(right))
            }
            EExpr::Cast { expr, to } => format!("({} as {})", self.expr(expr), to.name()),
            EExpr::Call {
                callee,
                name,
                arguments,
            } => {
                // A constant is named, not called.
                let constant = arguments.is_empty()
                    && self
                        .module
                        .fns
                        .iter()
                        .any(|function| function.reference == *callee && function.constant);
                if constant {
                    name.clone()
                } else {
                    format!("{name}({})", self.all(arguments).join(", "))
                }
            }
            EExpr::If {
                condition,
                then_block,
                else_block,
            } => format!(
                "if {} {} else {}",
                self.condition(condition),
                self.block(then_block),
                self.block(else_block)
            ),
            EExpr::Match {
                scrutinee,
                enum_name,
                arms,
            } => {
                let mut out = format!("match {} {{\n", self.expr(scrutinee));
                for arm in arms {
                    let payload: Vec<String> =
                        arm.payload.iter().map(|(_, name)| name.clone()).collect();
                    let pattern = variant_pattern(
                        &format!("{enum_name}::{}", arm.variant_name),
                        self.module.variant_fields(enum_name, &arm.variant_name),
                        &payload,
                    );
                    let body = self.block(&arm.body);
                    let _ = writeln!(out, "{pattern} => {body}");
                }
                out.push('}');
                out
            }
            EExpr::Block(block) => self.block(block),
            // Not in tail position: as a block of its own.
            EExpr::Loop { state, body, .. } => format!("{{\n{}}}", self.looping(state, body, None)),
            EExpr::For {
                index,
                lo,
                hi,
                state,
                body,
            } => {
                let header = format!("for {} in {}..{}", index.1, self.expr(lo), self.expr(hi));
                format!("{{\n{}}}", self.looping(state, body, Some(header)))
            }
            EExpr::Break(value) => format!("break {}", self.expr(value)),
            // Inside a larger expression: `return` would take whatever
            // follows it as part of its value.
            EExpr::Return(value) => format!("(return {})", self.expr(value)),
            EExpr::Continue(next) => format!("{{\n{}}}", self.continuing(next)),
        }
    }
}

/// Whether the printed expression has Rust's type `!`: it is a transfer of
/// control, a trap, or a panic, or a conditional or block that ends in one
/// on every path. Where it does, a wildcard in the pattern of a `let` must
/// be given some type, and `()` serves.
fn diverges(expr: &EExpr) -> bool {
    let block = |block: &EBlock| block.tail.as_deref().is_some_and(diverges);
    match expr {
        EExpr::Trap
        | EExpr::Panic { .. }
        | EExpr::Break(_)
        | EExpr::Continue(_)
        | EExpr::Return(_) => true,
        EExpr::If {
            then_block,
            else_block,
            ..
        } => block(then_block) && block(else_block),
        EExpr::Match { arms, .. } => arms.iter().all(|arm| block(&arm.body)),
        EExpr::Block(inner) => block(inner),
        _ => false,
    }
}

/// Whether an expression contains a point that never yields a value, a
/// transfer of control, a trap, or a panic, anywhere inside it. Rust types
/// such a point as `!`, and where it stands in a tuple or an arm the type of
/// the whole may stay undetermined, so a `let` bound to such an expression
/// is given its type. That is the only use of this: annotating too little
/// costs an error from rustc, and annotating too much costs nothing, since
/// every name's type is its own.
fn contains_divergence(expr: &EExpr) -> bool {
    let any = |exprs: &[EExpr]| exprs.iter().any(contains_divergence);
    let block = |block: &EBlock| {
        block.stmts.iter().any(|stmt| match stmt {
            EStmt::Let { value, .. } | EStmt::Assign { value, .. } => contains_divergence(value),
            EStmt::Expr(expr) => contains_divergence(expr),
        }) || block.tail.as_deref().is_some_and(contains_divergence)
    };
    let state = |state: &[(VarId, String, EType, EExpr)]| {
        state
            .iter()
            .any(|(_, _, _, init)| contains_divergence(init))
    };
    match expr {
        EExpr::Trap
        | EExpr::Panic { .. }
        | EExpr::Break(_)
        | EExpr::Continue(_)
        | EExpr::Return(_) => true,
        EExpr::Var { .. } | EExpr::Bool(_) | EExpr::Literal(..) | EExpr::Proved | EExpr::Ghost => {
            false
        }
        EExpr::Tuple(exprs)
        | EExpr::Variant { payload: exprs, .. }
        | EExpr::Call {
            arguments: exprs, ..
        } => any(exprs),
        EExpr::Struct { fields, .. } => fields.iter().any(|(_, value)| contains_divergence(value)),
        EExpr::Field { target, .. } | EExpr::Cast { expr: target, .. } => {
            contains_divergence(target)
        }
        EExpr::Method {
            receiver,
            arguments,
            ..
        } => contains_divergence(receiver) || any(arguments),
        EExpr::Compare { left, right, .. } => {
            contains_divergence(left) || contains_divergence(right)
        }
        EExpr::If {
            condition,
            then_block,
            else_block,
        } => contains_divergence(condition) || block(then_block) || block(else_block),
        EExpr::Match {
            scrutinee, arms, ..
        } => contains_divergence(scrutinee) || arms.iter().any(|arm| block(&arm.body)),
        EExpr::Block(inner) => block(inner),
        EExpr::Loop { state: s, body, .. } => state(s) || block(body),
        EExpr::For {
            lo,
            hi,
            state: s,
            body,
            ..
        } => contains_divergence(lo) || contains_divergence(hi) || state(s) || block(body),
    }
}

/// A literal with its type as a suffix; a negative one in parentheses, so
/// that a method call or a cast applies to the literal and not to its
/// magnitude.
fn literal(ty: MachineInt, value: i128) -> String {
    if value < 0 {
        format!("({value}_{})", ty.name())
    } else {
        format!("{value}_{}", ty.name())
    }
}

fn pattern_of(pattern: &EPattern) -> String {
    match pattern {
        EPattern::Bind {
            name,
            mutable: true,
            ..
        } => format!("mut {name}"),
        EPattern::Bind { name, .. } => name.clone(),
        EPattern::Wildcard => "_".into(),
        EPattern::Tuple(patterns) => {
            let patterns: Vec<String> = patterns.iter().map(pattern_of).collect();
            tuple_of(&patterns)
        }
    }
}

impl Value {
    /// The value as Rust's `{:?}` would print it, for comparing a compiled
    /// program's output with the interpreter's.
    pub fn debug(&self, module: &Module) -> String {
        let all = |values: &[Value]| -> Vec<String> {
            values.iter().map(|value| value.debug(module)).collect()
        };
        match self {
            Self::Bool(flag) => flag.to_string(),
            Self::Int(_, value) => value.to_string(),
            Self::Proved => "Proved".into(),
            Self::Ghost => "Ghost".into(),
            Self::Tuple(fields) => tuple_of(&all(fields)),
            Self::Struct(id, fields) => {
                let Some(item) = module.structs.iter().find(|item| item.id == *id) else {
                    return "UnknownStruct".into();
                };
                let fields: Vec<String> = item
                    .fields
                    .iter()
                    .zip(all(fields))
                    .map(|((name, _), value)| format!("{name}: {value}"))
                    .collect();
                format!("{} {{ {} }}", item.name, fields.join(", "))
            }
            Self::Variant(id, index, payload) => {
                let variant = module
                    .enums
                    .iter()
                    .find(|item| item.id == *id)
                    .and_then(|item| item.variants.get(*index));
                let Some(variant) = variant else {
                    return "UnknownVariant".into();
                };
                variant_of(&variant.name, variant.fields.as_deref(), &all(payload))
            }
        }
    }
}

impl Module {
    /// The field names of a variant written with braces, by the names of
    /// the enum and the variant, which are unique in a module.
    fn variant_fields(&self, enum_name: &str, variant_name: &str) -> Option<&[String]> {
        self.enums
            .iter()
            .find(|item| item.name == enum_name)?
            .variants
            .iter()
            .find(|variant| variant.name == variant_name)?
            .fields
            .as_deref()
    }
}

/// A variant pattern as Rust writes it: `V`, `V(a, _)`, or, for a variant
/// with named fields, `V { a, b: y, .. }`: a field bound to its own name is
/// written once, as Rust's lint asks, and the fields bound to `_` are left
/// to `..`.
fn variant_pattern(name: &str, fields: Option<&[String]>, bound: &[String]) -> String {
    let Some(fields) = fields else {
        return variant_of(name, None, bound);
    };
    let mut written: Vec<String> = Vec::new();
    for (field, name) in fields.iter().zip(bound) {
        if name == "_" {
            continue;
        }
        written.push(if name == field {
            field.clone()
        } else {
            format!("{field}: {name}")
        });
    }
    if written.len() < fields.len() {
        written.push("..".into());
    }
    if written.is_empty() {
        format!("{name} {{}}")
    } else {
        format!("{name} {{ {} }}", written.join(", "))
    }
}

/// A variant with its payload as Rust writes it: `V`, `V(a, b)`, or, for a
/// variant with named fields, `V { a: x, b: y }`, in a declaration, an
/// expression, and a value alike.
fn variant_of(name: &str, fields: Option<&[String]>, payload: &[String]) -> String {
    match fields {
        Some(fields) => {
            let fields: Vec<String> = fields
                .iter()
                .zip(payload)
                .map(|(field, value)| format!("{field}: {value}"))
                .collect();
            format!("{name} {{ {} }}", fields.join(", "))
        }
        None if payload.is_empty() => name.to_string(),
        None => format!("{name}({})", payload.join(", ")),
    }
}
