//! The erased tree printed as plain Rust, with cleanup for readability.
//!
//! Cleanup removes dead marker storage while retaining runtime calls,
//! control transfers, evaluation order and runtime destruction scopes. Unused
//! logical pattern names become wildcards; unused runtime names are prefixed
//! without removing their bindings. Signatures and aggregate layouts remain.
//!
//! Every logical position prints as the single private-constructible Erased
//! marker. A module includes marker support only when its output uses it.
//! There are no crate-wide lint allowances. A retained source construct that
//! intentionally triggers a Rust lint receives a specific local allowance
//! with an explanation (for example, literal arithmetic that must panic).
//!
//! Reference parameters print as Rust references. Whole-place reads and
//! writes dereference them; field accesses use Rust's automatic dereference.
//! Lending a reference parameter again is an explicit reborrow. User methods
//! print by their canonical Type::method path, with explicit receiver values
//! or lends, so an explicitly named method retains its meaning.
//!
//! Integer literals carry their type; negative literals, casts and operator
//! operands are parenthesized where needed to preserve grouping. A binding
//! initialized by a diverging expression carries a type annotation because
//! Rust may have no returned value from which to infer its type.

use std::collections::{BTreeMap, HashSet};
use std::fmt::Write;

use crate::kernel::{MachineInt, Op, Prim, VarId};
use crate::typed::{CompareOp, Derive, Passing};

use super::cleanup::{self, Visit};
use super::interp::Value;
use super::tree::{EBlock, EExpr, EFn, EPattern, EPlace, EStmt, EType, Module};

const HEADER: &str = "// Generated by Locus. Do not edit.\n";

/// The markers, defined once for all the generated modules (Target language:
/// What is generated). Each is a struct with a private field, so that no
/// code outside the module that defines them, and the modules under it, can
/// make one: the only value is the private constant of the same name, which
/// the generated code names as it names the type. `Debug` is written by
/// hand so that a marker prints as its name, as the interpreter prints it.
///
/// That a marker cannot be made from nothing stops casual misuse and is no
/// part of the guarantee: hand-written Rust can obtain a marker honestly,
/// from any function that returns evidence, and the guarantee rests on no
/// exported function taking one, which the elaborator checks.
pub const MARKERS: &str = "\
/// An erased logical value; construction is private to generated code.
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct Erased {
    _private: (),
}

// The private value shares the marker type's readable spelling.
#[allow(non_upper_case_globals, dead_code)]
const Erased: Erased = Erased { _private: () };

impl std::fmt::Debug for Erased {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(\"Erased\")
    }
}
";

/// Where the markers are: defined in the module printed, which is what
/// `locus rust` prints for one file, or in the root of the generated crate,
/// from which each module under it imports them (`locus build`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Markers {
    Here,
    InRoot,
}

/// What each generated item and field is marked with, as the printer writes
/// it: `pub`, `pub(crate)`, `pub(super)`, `pub(in path)`, or nothing for
/// private. The erased tree does not carry it, since it is no runtime
/// matter; the elaborator records it beside the tree, and the printer looks
/// each name up in its namespace, types or values. A name not recorded is
/// private, which is what an item is without `pub`.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Visibilities {
    types: BTreeMap<String, String>,
    values: BTreeMap<String, String>,
    /// By the struct's name and the field's.
    fields: BTreeMap<(String, String), String>,
    /// Everything `pub`, whatever was recorded: for a tree built by hand,
    /// which has no visibilities, and for a test that calls into the module
    /// from outside it.
    everything_public: bool,
}

impl Visibilities {
    /// Every item and field `pub`.
    pub fn everything_public() -> Self {
        Self {
            everything_public: true,
            ..Self::default()
        }
    }

    /// Records a struct's or an enum's visibility, spelled as Rust spells
    /// it, or as the empty string for private.
    pub fn set_type(&mut self, name: &str, spelling: &str) {
        self.types.insert(name.to_string(), spelling.to_string());
    }

    /// Records a function's or a constant's visibility.
    pub fn set_value(&mut self, name: &str, spelling: &str) {
        self.values.insert(name.to_string(), spelling.to_string());
    }

    /// Records a struct field's visibility.
    pub fn set_field(&mut self, item: &str, field: &str, spelling: &str) {
        self.fields
            .insert((item.to_string(), field.to_string()), spelling.to_string());
    }

    /// The spelling with the space after it, or nothing for private.
    fn spelled(&self, recorded: Option<&String>) -> String {
        if self.everything_public {
            return "pub ".into();
        }
        match recorded.map(String::as_str) {
            None | Some("") => String::new(),
            Some(spelling) => format!("{spelling} "),
        }
    }

    fn of_type(&self, name: &str) -> String {
        self.spelled(self.types.get(name))
    }

    fn of_value(&self, name: &str) -> String {
        self.spelled(self.values.get(name))
    }

    fn of_field(&self, item: &str, field: &str) -> String {
        self.spelled(self.fields.get(&(item.to_string(), field.to_string())))
    }
}

struct Printer<'m> {
    module: &'m Module,
    out: String,
    /// The reference parameters of the function being printed: a mention
    /// of one as a whole is written through `*`.
    refs: HashSet<VarId>,
}

/// The module as Rust source with every item and field `pub` and the
/// markers defined in it: the printing of a tree built by hand, which has no
/// visibilities, and of a test's module that is called from outside.
pub fn print_module(module: &Module) -> String {
    print_module_with(module, &Visibilities::everything_public(), Markers::Here)
}

/// The module as Rust source: the header, the markers or their import, and
/// the items with the visibilities recorded for them.
pub fn print_module_with(module: &Module, visibilities: &Visibilities, markers: Markers) -> String {
    let module = cleanup::module(module);
    let body = items(&module, visibilities);
    let mut source = String::from(HEADER);
    for name in ["Erased"] {
        if mentions(&body, name) {
            match markers {
                Markers::Here => source.push_str(&marker_support(name)),
                Markers::InRoot => {
                    let _ = writeln!(source, "use crate::{name};");
                }
            }
        }
    }
    source.push_str(&body);
    indent(&source)
}

/// The items alone, without the header and the markers: what a report of a
/// program shows.
pub fn print_items(module: &Module, visibilities: &Visibilities) -> String {
    indent(&items(&cleanup::module(module), visibilities))
}

/// The root of a generated crate, `src/lib.rs`: the header, the markers, and
/// one `pub mod` for each module under it, in the order given.
pub fn print_root(modules: &[String]) -> String {
    let mut source = String::from(HEADER);
    source.push_str(MARKERS);
    for module in modules {
        let _ = writeln!(source, "\npub mod {module};");
    }
    indent(&source)
}

/// Build roots only define support imported by one of their modules.
pub(crate) fn print_root_for_modules(modules: &[(String, String)]) -> String {
    let mut source = String::from(HEADER);
    for name in ["Erased"] {
        if modules.iter().any(|(_, body)| {
            body.lines()
                .any(|line| line == format!("use crate::{name};"))
        }) {
            source.push_str(&marker_support(name));
        }
    }
    for (name, _) in modules {
        let _ = writeln!(source, "\npub mod {name};");
    }
    indent(&source)
}

fn mentions(source: &str, name: &str) -> bool {
    source
        .split(|character: char| !character.is_alphanumeric() && character != '_')
        .any(|word| word == name)
}

fn marker_support(name: &str) -> String {
    format!(
        r#"
/// An erased logical value; construction is private to generated code.
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct {name} {{
    _private: (),
}}

// The private value shares the marker type's readable spelling.
#[allow(non_upper_case_globals, dead_code)]
const {name}: {name} = {name} {{ _private: () }};

impl std::fmt::Debug for {name} {{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        f.write_str("{name}")
    }}
}}
"#
    )
}

/// The items, before indentation.
fn items(module: &Module, visibilities: &Visibilities) -> String {
    let mut printer = Printer {
        module,
        out: String::new(),
        refs: HashSet::new(),
    };
    for item in &module.structs {
        printer.derives(&item.derives);
        let visibility = visibilities.of_type(&item.name);
        printer.private_item(&visibility);
        let _ = writeln!(
            printer.out,
            "{visibility}struct {}{} {{",
            item.name,
            lifetime_parameters(item.fields.iter().map(|(_, ty)| ty))
        );
        for (name, ty) in &item.fields {
            let ty = printer.ty(ty);
            let visibility = visibilities.of_field(&item.name, name);
            if visibility != "pub " {
                printer.out.push_str("    // Preserve this private source field even when runtime code never reads it.\n    #[allow(dead_code)]\n");
            }
            let _ = writeln!(printer.out, "    {visibility}{name}: {ty},");
        }
        printer.out.push_str("}\n");
    }
    for item in &module.enums {
        printer.derives(&item.derives);
        let visibility = visibilities.of_type(&item.name);
        printer.private_item(&visibility);
        let _ = writeln!(
            printer.out,
            "{visibility}enum {}{} {{",
            item.name,
            lifetime_parameters(item.variants.iter().flat_map(|v| v.payload.iter()))
        );
        for variant in &item.variants {
            let payload: Vec<String> = variant.payload.iter().map(|ty| printer.ty(ty)).collect();
            if let Some(fields) = &variant.fields {
                let fields: Vec<String> = fields
                    .iter()
                    .zip(&payload)
                    .map(|(name, ty)| format!("{name}: {ty}"))
                    .collect();
                let _ = writeln!(
                    printer.out,
                    "    {} {{ {} }},",
                    variant.name,
                    fields.join(", ")
                );
            } else if payload.is_empty() {
                let _ = writeln!(printer.out, "    {},", variant.name);
            } else {
                let _ = writeln!(printer.out, "    {}({}),", variant.name, payload.join(", "));
            }
        }
        printer.out.push_str("}\n");
    }
    for function in module
        .fns
        .iter()
        .filter(|function| function.owner.is_none())
    {
        printer.function(function, visibilities);
    }
    // The functions of each `impl` block, in the order the blocks' types
    // are first met, each block once whatever order the file wrote them in.
    let mut owners: Vec<&str> = Vec::new();
    for function in &module.fns {
        if let Some(owner) = &function.owner
            && !owners.contains(&owner.as_str())
        {
            owners.push(owner);
        }
    }
    for owner in owners {
        let _ = write!(printer.out, "\nimpl {owner} {{");
        for function in module
            .fns
            .iter()
            .filter(|function| function.owner.as_deref() == Some(owner))
        {
            printer.function(function, visibilities);
        }
        printer.out.push_str("}\n");
    }
    printer.out
}

/// Indents by brace depth. The printer emits one statement per line, and a
/// string literal, which is the message of a panic or of a trap, stays on
/// its line, so counting the braces outside literals is exact.
fn indent(source: &str) -> String {
    let mut out = String::new();
    let mut depth = 0usize;
    for line in source.lines() {
        let line = line.trim();
        let closes_first = line.starts_with('}');
        if closes_first {
            depth = depth.saturating_sub(1);
        }
        if !line.is_empty() {
            out.push_str(&"    ".repeat(depth));
            out.push_str(line);
        }
        out.push('\n');
        let (opens, closes) = braces(line);
        depth = (depth + opens).saturating_sub(closes - usize::from(closes_first));
    }
    out
}

/// The opening and closing braces of a line, outside its string literals.
fn braces(line: &str) -> (usize, usize) {
    let (mut opens, mut closes) = (0, 0);
    let mut in_literal = false;
    let mut chars = line.chars();
    while let Some(c) = chars.next() {
        match c {
            '\\' if in_literal => {
                chars.next();
            }
            '"' => in_literal = !in_literal,
            '{' if !in_literal => opens += 1,
            '}' if !in_literal => closes += 1,
            _ => {}
        }
    }
    (opens, closes)
}

fn tuple_of(items: &[String]) -> String {
    match items {
        [only] => format!("({only},)"),
        _ => format!("({})", items.join(", ")),
    }
}

impl Printer<'_> {
    /// One function, or one method of an `impl` block, after a blank line.
    fn function(&mut self, function: &EFn, visibilities: &Visibilities) {
        self.out.push('\n');
        let native = function.body.stmts.iter().any(|stmt| matches!(stmt, EStmt::Let { value: EExpr::Buffer { .. }, .. } | EStmt::Expr(EExpr::Buffer { .. })) || matches!(stmt,EStmt::Let{value:EExpr::Shared{value,..},..} if matches!(**value,EExpr::Buffer{..})));
        let visibility = if native {
            String::new()
        } else {
            visibilities.of_value(&function.name)
        };
        self.private_item(&visibility);
        for (lint, why) in required_lints(&function.body) {
            let _ = writeln!(self.out, "// {why}\n#[allow({lint})]");
        }
        let result = self.ty(&function.result);
        // A constant is a `const` item: its body is one expression, which
        // Rust computes at compile time (the elaborator saw that it can).
        if function.constant
            && function.params.is_empty()
            && function.body.stmts.is_empty()
            && let Some(value) = &function.body.tail
        {
            let value = self.expr(value);
            let _ = writeln!(
                self.out,
                "\n{visibility}const {}: {result} = {value};",
                function.method_name()
            );
            return;
        }
        self.refs = function
            .params
            .iter()
            .enumerate()
            .filter(|(index, _)| function.passing_of(*index).is_reference())
            .map(|(_, (id, _, _))| *id)
            .collect();
        let params: Vec<String> = function
            .params
            .iter()
            .enumerate()
            .map(|(index, (_, name, ty))| {
                let reference_ty = match ty {
                    EType::Ref(lifetime, inner) if function.passing_of(index).is_reference() => {
                        Some((lifetime, inner))
                    }
                    _ => None,
                };
                let ty = self.ty(ty);
                if let Some((lifetime, inner)) = reference_ty {
                    let lifetime = lifetime
                        .as_ref()
                        .map(|l| format!("{l} "))
                        .unwrap_or_default();
                    let mutable = if function.passing_of(index) == Passing::RefMut {
                        "mut "
                    } else {
                        ""
                    };
                    return format!("{name}: &{lifetime}{mutable}{}", self.ty(inner));
                }
                match (function.receiver && index == 0, function.passing_of(index)) {
                    (true, Passing::Value) => "self".into(),
                    (true, Passing::MutValue) => "mut self".into(),
                    (true, Passing::Ref) => "&self".into(),
                    (true, Passing::RefMut) => "&mut self".into(),
                    (false, Passing::Value) => format!("{name}: {ty}"),
                    (false, Passing::MutValue) => format!("mut {name}: {ty}"),
                    (false, Passing::Ref) => format!("{name}: &{ty}"),
                    (false, Passing::RefMut) => format!("{name}: &mut {ty}"),
                }
            })
            .collect();
        let _ = write!(
            self.out,
            "\n{visibility}fn {}{}({}) -> {result} ",
            function.method_name(),
            lifetime_parameters(
                function
                    .params
                    .iter()
                    .map(|(_, _, ty)| ty)
                    .chain(std::iter::once(&function.result))
            ),
            params.join(", ")
        );
        let body = self.block(&function.body);
        self.out.push_str(&body);
        self.out.push('\n');
    }

    fn private_item(&mut self, visibility: &str) {
        if visibility != "pub " {
            self.out.push_str("// This source item need not have a caller in this generated crate.\n#[allow(dead_code)]\n");
        }
    }

    /// The `#[derive(...)]` line before a struct or an enum, when it
    /// derives anything, after the blank line that separates items.
    fn derives(&mut self, derives: &[Derive]) {
        self.out.push('\n');
        if derives.is_empty() {
            return;
        }
        let names: Vec<&str> = derives.iter().map(|derive| derive.name()).collect();
        let _ = writeln!(self.out, "#[derive({})]", names.join(", "));
    }

    fn ty(&self, ty: &EType) -> String {
        match ty {
            EType::Ref(lifetime, inner) => format!(
                "&{}{}",
                lifetime
                    .as_ref()
                    .map(|l| format!("{l} "))
                    .unwrap_or_default(),
                self.ty(inner)
            ),
            EType::StructApplied(id, args) => {
                format!("{}<{}>", self.ty(&EType::Struct(*id)), args.join(", "))
            }
            EType::EnumApplied(id, args) => {
                format!("{}<{}>", self.ty(&EType::Enum(*id)), args.join(", "))
            }
            EType::Boxed(element) => format!("Box<{}>", self.ty(element)),
            EType::Buffer(element) => format!("Vec<{}>", self.ty(element)),
            EType::Array(element, n) => format!("[{}; {n}]", self.ty(element)),
            EType::Slice(element) => format!("[{}]", self.ty(element)),
            EType::Bool => "bool".into(),
            EType::Int(ty) => ty.name().into(),
            EType::Proved | EType::Ghost => "Erased".into(),
            EType::Tuple(fields) => {
                let fields: Vec<String> = fields.iter().map(|field| self.ty(field)).collect();
                tuple_of(&fields)
            }
            EType::Struct(id) => self
                .module
                .structs
                .iter()
                .find(|item| item.id == *id)
                .map_or_else(|| "UnknownStruct".into(), |item| item.name.clone()),
            EType::Enum(id) => self
                .module
                .enums
                .iter()
                .find(|item| item.id == *id)
                .map_or_else(|| "UnknownEnum".into(), |item| item.name.clone()),
            EType::Fn(params, result) => {
                let params: Vec<String> = params.iter().map(|param| self.ty(param)).collect();
                format!("fn({}) -> {}", params.join(", "), self.ty(result))
            }
        }
    }

    fn block(&mut self, block: &EBlock) -> String {
        format!("{{\n{}}}", self.contents(block))
    }

    /// A block's statements and tail, without its braces. A nested block in
    /// tail position is written straight into the enclosing block instead of
    /// getting braces of its own.
    fn contents(&mut self, block: &EBlock) -> String {
        let mut out = String::new();
        for stmt in &block.stmts {
            match stmt {
                EStmt::Let { pattern, value } => {
                    let annotation =
                        if contains_divergence(value) && !matches!(pattern, EPattern::Wildcard) {
                            format!(": {}", self.pattern_type(pattern, diverges(value)))
                        } else {
                            String::new()
                        };
                    if contains_divergence(value) && !matches!(pattern, EPattern::Wildcard) {
                        out.push_str("// A retained control transfer can make every later use of this binding unreachable.\n#[allow(unused_variables)]\n");
                    }
                    let value = self.expr(value);
                    let _ = writeln!(out, "let {}{annotation} = {value};", pattern_of(pattern));
                }
                EStmt::Assign { place, value } => {
                    let value = self.expr(value);
                    let target = self.place(place);
                    let _ = writeln!(out, "{target} = {value};");
                }
                EStmt::Expr(expr) => {
                    let expr = self.standing_alone(expr);
                    let _ = writeln!(out, "{expr};");
                }
            }
        }
        match block.tail.as_deref() {
            None => {}
            Some(EExpr::Block(inner)) => out.push_str(&self.contents(inner)),
            Some(tail) => {
                out.push_str(&self.standing_alone(tail));
                out.push('\n');
            }
        }
        out
    }

    /// An expression that is a whole statement or a whole tail, where a
    /// `return` or a `break` needs no parentheses.
    fn standing_alone(&mut self, expr: &EExpr) -> String {
        match expr {
            EExpr::Return(value) => self.returning(value),
            EExpr::Break(Some(value)) => format!("break {}", self.expr(value)),
            other => self.expr(other),
        }
    }

    /// `return value`, or `return` alone when the value is `()`, as it
    /// was written.
    fn returning(&mut self, value: &EExpr) -> String {
        match value {
            EExpr::Tuple(fields) if fields.is_empty() => "return".into(),
            value => format!("return {}", self.expr(value)),
        }
    }

    /// The type of a pattern, for an annotation. A wildcard has no type of
    /// its own. Its part is left to Rust to infer, unless the value has the
    /// type `!` (`diverges`), when there is nothing to infer it from and any
    /// type will do, since no value ever reaches the pattern: it is `()`.
    fn pattern_type(&self, pattern: &EPattern, diverges: bool) -> String {
        match pattern {
            EPattern::Bind { ty, .. } => self.ty(ty),
            EPattern::Wildcard if diverges => "()".into(),
            EPattern::Wildcard => "_".into(),
            EPattern::Tuple(patterns) => {
                let types: Vec<String> = patterns
                    .iter()
                    .map(|pattern| self.pattern_type(pattern, diverges))
                    .collect();
                tuple_of(&types)
            }
        }
    }

    /// A condition, without the parentheses a comparison gets elsewhere.
    fn condition(&mut self, expr: &EExpr) -> String {
        let printed = self.expr(expr);
        match expr {
            EExpr::Compare { .. } => printed[1..printed.len() - 1].to_string(),
            _ => printed,
        }
    }

    /// The target of a field access, the receiver of a method, or the
    /// operand of a cast: an operator expression there is parenthesized,
    /// since the postfix forms and `as` bind tighter than any operator.
    fn postfix_operand(&mut self, operand: &EExpr) -> String {
        let printed = self.expr(operand);
        if matches!(operand, EExpr::Operate { .. }) {
            format!("({printed})")
        } else {
            printed
        }
    }

    /// The target of a field access or the receiver of a method, where
    /// Rust reaches through a reference by itself: a reference parameter is
    /// written bare.
    fn through_reference(&mut self, operand: &EExpr) -> String {
        match operand {
            EExpr::Var { id, name } if self.refs.contains(id) => name.clone(),
            other => self.postfix_operand(other),
        }
    }

    /// A place, as the left side of an assignment or the operand of a
    /// lend: `x.f.0`, or `*x` for the whole of a reference parameter.
    fn place(&self, place: &EPlace) -> String {
        let mut target = place.name.clone();
        for (index, name) in &place.path {
            match name {
                Some(name) => target.push_str(&format!(".{name}")),
                None => target.push_str(&format!(".{index}")),
            }
        }
        if place.path.is_empty() && self.refs.contains(&place.id) {
            format!("*{target}")
        } else {
            target
        }
    }

    /// An operand of an operator, parenthesized where Rust's precedence
    /// would otherwise read it differently from the tree; see the module
    /// comment.
    fn operand(&mut self, operand: &EExpr, around: Op, right: bool) -> String {
        let printed = self.expr(operand);
        let needs_parens = match operand {
            // A right operand of the same precedence, and a negation of a
            // negation, which Rust lints as a double negation.
            EExpr::Operate { op, .. } => {
                precedence(*op) < precedence(around)
                    || (precedence(*op) == precedence(around) && (right || around == Op::Neg))
            }
            EExpr::If { .. }
            | EExpr::Match { .. }
            | EExpr::Block(_)
            | EExpr::Loop { .. }
            | EExpr::While { .. }
            | EExpr::For { .. }
            | EExpr::Continue
            | EExpr::Break(_) => true,
            _ => false,
        };
        if needs_parens {
            format!("({printed})")
        } else {
            printed
        }
    }

    fn all(&mut self, exprs: &[EExpr]) -> Vec<String> {
        exprs.iter().map(|expr| self.expr(expr)).collect()
    }

    fn buffer(
        &mut self,
        op: crate::kernel::BufferOp,
        storage: crate::exec::BufferStorage,
        arguments: &[EExpr],
    ) -> String {
        use crate::kernel::BufferOp;
        let args = self.all(arguments);
        match op {
            BufferOp::Literal => match storage {
                crate::exec::BufferStorage::Vector => format!("vec![{}]", args.join(", ")),
                _ => format!("[{}]", args.join(", ")),
            },
            BufferOp::Length => format!("({}).len() as u64", args[0]),
            BufferOp::Get => format!(
                "({})[usize::try_from({}).expect(\"collection index does not fit usize\")]",
                args[0], args[1]
            ),
            BufferOp::Set => format!(
                "{{ let target = {}; let index = {}; let value = {}; target[usize::try_from(index).expect(\"collection index does not fit usize\")] = value; }}",
                args[0], args[1], args[2]
            ),
            BufferOp::Push => format!(
                "{{ let target = {}; let value = {}; target.push(value); }}",
                args[0], args[1]
            ),
        }
    }

    fn expr(&mut self, expr: &EExpr) -> String {
        match expr {
            EExpr::Shared { value, .. } => format!("&({})", self.expr(value)),
            EExpr::BoxNew(value) => format!("Box::new({})", self.expr(value)),
            EExpr::BoxDeref(value) => format!("*({})", self.expr(value)),
            EExpr::Deref(value) => format!("*({})", self.expr(value)),
            EExpr::Buffer {
                op,
                storage,
                arguments,
                ..
            } => self.buffer(*op, *storage, arguments),
            // A reference parameter mentioned as a whole is the value
            // behind it.
            EExpr::Var { id, name } if self.refs.contains(id) => format!("*{name}"),
            EExpr::Var { name, .. } => name.clone(),
            EExpr::Bool(value) => value.to_string(),
            EExpr::Literal(ty, value) => literal(*ty, *value),
            EExpr::Proved | EExpr::Ghost => "Erased".into(),
            EExpr::Trap => "unreachable!(\"shown never to be reached\")".into(),
            EExpr::Panic { form, argument } => match argument {
                Some(argument) => format!("{}!(\"{{}}\", {argument:?})", form.name()),
                None => format!("{}!()", form.name()),
            },
            EExpr::Assert {
                debug,
                condition,
                message,
            } => {
                let name = if *debug { "debug_assert" } else { "assert" };
                let condition = self.condition(condition);
                format!("{name}!({condition}, \"{{}}\", {message:?})")
            }
            EExpr::Tuple(fields) => tuple_of(&self.all(fields)),
            EExpr::Struct { name, fields, .. } => {
                let fields: Vec<String> = fields
                    .iter()
                    .map(|(field, value)| format!("{field}: {}", self.expr(value)))
                    .collect();
                format!("{name} {{ {} }}", fields.join(", "))
            }
            EExpr::Variant {
                enum_name,
                variant_name,
                payload,
                ..
            } => {
                let name = format!("{enum_name}::{variant_name}");
                let fields = self.module.variant_fields(enum_name, variant_name);
                let payload = self.all(payload);
                match fields {
                    // `V { a, b: y }`: a field given its own name is written once.
                    Some(fields) => {
                        let fields: Vec<String> = fields
                            .iter()
                            .zip(payload)
                            .map(|(field, value)| {
                                if *field == value {
                                    value
                                } else {
                                    format!("{field}: {value}")
                                }
                            })
                            .collect();
                        format!("{name} {{ {} }}", fields.join(", "))
                    }
                    None => variant_of(&name, None, &payload),
                }
            }
            EExpr::Field {
                target,
                index,
                name,
            } => {
                let target = self.through_reference(target);
                match name {
                    Some(name) => format!("{target}.{name}"),
                    None => format!("{target}.{index}"),
                }
            }
            EExpr::Method {
                prim,
                receiver,
                arguments,
            } => {
                let method = match prim {
                    Prim::Op(op, _) => op.name(),
                    other => other.name(),
                };
                format!(
                    "{}.{method}({})",
                    self.through_reference(receiver),
                    self.all(arguments).join(", ")
                )
            }
            EExpr::Compare { op, left, right } => {
                let op = match op {
                    CompareOp::Eq => "==",
                    CompareOp::Ne => "!=",
                    CompareOp::Lt => "<",
                    CompareOp::Le => "<=",
                    CompareOp::Gt => ">",
                    CompareOp::Ge => ">=",
                };
                format!("({} {op} {})", self.expr(left), self.expr(right))
            }
            EExpr::Cast { expr, to } => {
                format!("({} as {})", self.postfix_operand(expr), to.name())
            }
            EExpr::Operate {
                op,
                operands,
                proven_safe: false,
                ..
            } if op.panic() == crate::kernel::Panic::Overflow => {
                let method = format!("checked_{}", op.name());
                let receiver = format!("({})", self.expr(&operands[0]));
                let args = self.all(&operands[1..]).join(", ");
                let message = match op {
                    crate::kernel::Op::Add => "attempt to add with overflow",
                    crate::kernel::Op::Sub => "attempt to subtract with overflow",
                    crate::kernel::Op::Mul => "attempt to multiply with overflow",
                    crate::kernel::Op::Neg => "attempt to negate with overflow",
                    _ => unreachable!(),
                };
                format!("{receiver}.{method}({args}).expect(\"{message}\")")
            }
            EExpr::Operate { op, operands, .. } => match operands.as_slice() {
                [operand] => format!("-{}", self.operand(operand, *op, false)),
                [left, right] => format!(
                    "{} {} {}",
                    self.operand(left, *op, false),
                    op.symbol(),
                    self.operand(right, *op, true)
                ),
                _ => unreachable!("a row has one or two operands"),
            },
            EExpr::Call {
                callee,
                name,
                arguments,
            } => {
                // A constant is named, not called.
                let constant = arguments.is_empty()
                    && self
                        .module
                        .fns
                        .iter()
                        .any(|function| function.reference == *callee && function.constant);
                if constant {
                    name.clone()
                } else {
                    format!("{name}({})", self.all(arguments).join(", "))
                }
            }
            EExpr::Lend { mutable, place } => {
                let place = self.place(place);
                if *mutable {
                    format!("&mut {place}")
                } else {
                    format!("&{place}")
                }
            }
            EExpr::If {
                condition,
                then_block,
                else_block,
            } => format!(
                "if {} {} else {}",
                self.condition(condition),
                self.block(then_block),
                self.block(else_block)
            ),
            EExpr::Match {
                scrutinee,
                enum_name,
                arms,
            } => {
                let mut out = format!("match {} {{\n", self.expr(scrutinee));
                for arm in arms {
                    let payload: Vec<String> =
                        arm.payload.iter().map(|(_, name)| name.clone()).collect();
                    let pattern = variant_pattern(
                        &format!("{enum_name}::{}", arm.variant_name),
                        self.module.variant_fields(enum_name, &arm.variant_name),
                        &payload,
                    );
                    let body = self.block(&arm.body);
                    let _ = writeln!(out, "{pattern} => {body}");
                }
                out.push('}');
                out
            }
            EExpr::Block(block) => self.block(block),
            EExpr::Loop { body, .. } => format!("loop {}", self.block(body)),
            EExpr::While { condition, body } => {
                format!("while {} {}", self.condition(condition), self.block(body))
            }
            EExpr::For {
                index,
                lo,
                hi,
                inclusive,
                body,
            } => {
                let range = if *inclusive { "..=" } else { ".." };
                format!(
                    "for {} in {}{range}{} {}",
                    index.1,
                    self.expr(lo),
                    self.expr(hi),
                    self.block(body)
                )
            }
            EExpr::Break(None) => "break".into(),
            // Inside a larger expression: `return` and `break` would take
            // whatever follows them as part of their value.
            EExpr::Break(Some(value)) => format!("(break {})", self.expr(value)),
            EExpr::Return(value) => format!("({})", self.returning(value)),
            EExpr::Continue => "continue".into(),
        }
    }
}

/// Lints attached only to a function containing the construct that requires
/// them. Source evaluation, including failing arithmetic, is kept intact.
fn required_lints(block: &EBlock) -> Vec<(&'static str, &'static str)> {
    #[derive(Default)]
    struct Scan {
        parens: bool,
        arithmetic: bool,
        assignments: bool,
        divergence: bool,
        comparisons: bool,
        braces: bool,
        self_assignment: bool,
    }
    impl Visit for Scan {
        fn stmt(&mut self, stmt: &EStmt) {
            self.assignments |= matches!(stmt, EStmt::Assign { .. });
            if let EStmt::Assign { place, value } = stmt {
                fn same_place(value: &EExpr, place: &EPlace, depth: usize) -> bool {
                    match value {
                        EExpr::Var { id, .. } => depth == 0 && *id == place.id,
                        EExpr::Field { target, index, .. } if depth > 0 => {
                            *index == place.path[depth - 1].0
                                && same_place(target, place, depth - 1)
                        }
                        _ => false,
                    }
                }
                self.self_assignment |= same_place(value, place, place.path.len());
            }
            if let EStmt::Let { value, .. } | EStmt::Expr(value) = stmt {
                self.divergence |= contains_divergence(value);
            }
            cleanup::walk_stmt(self, stmt);
        }
        fn expr(&mut self, expr: &EExpr) {
            match expr {
                EExpr::Compare { .. } => {
                    self.parens = true;
                    self.comparisons = true;
                }
                EExpr::Cast { .. } | EExpr::Return(_) | EExpr::Break(Some(_)) => self.parens = true,
                EExpr::Literal(_, value) if *value < 0 => self.parens = true,
                EExpr::Operate { .. } => self.arithmetic = true,
                EExpr::Block(_) => self.braces = true,
                _ => {}
            }
            self.divergence |= matches!(
                expr,
                EExpr::Return(_)
                    | EExpr::Break(_)
                    | EExpr::Continue
                    | EExpr::Panic { .. }
                    | EExpr::Trap
            );
            cleanup::walk_expr(self, expr);
        }
    }
    let mut scan = Scan::default();
    scan.block(block);
    let mut found = Vec::new();
    if scan.self_assignment {
        found.push((
            "dead_code",
            "Retain explicit self-assignments; Rust's dead_code lint also diagnoses these stores.",
        ));
    }
    if scan.parens {
        found.push((
            "unused_parens",
            "Parentheses preserve the source expression's grouping in every context.",
        ));
    }
    if scan.comparisons {
        found.push((
            "unused_comparisons",
            "Retain comparisons even when a machine type makes their result constant.",
        ));
    }
    if scan.braces {
        found.push((
            "unused_braces",
            "Retain expression block boundaries and their destruction scopes.",
        ));
    }
    if scan.assignments {
        found.push((
            "unused_assignments",
            "Retain runtime stores, including those whose old value is never read.",
        ));
    }
    if scan.divergence {
        found.push((
            "unreachable_code",
            "Retain source control transfers and any subsequent unreachable expressions.",
        ));
    }
    if scan.arithmetic {
        found.push((
            "arithmetic_overflow, unconditional_panic, overflowing_literals",
            "An operation that fails on literals still has the source's runtime panic behavior.",
        ));
    }
    found
}

/// Whether the printed expression has Rust's type `!`: it is a transfer of
/// control, a trap, or a panic, or a conditional or block that ends in one
/// on every path. Where it does, a wildcard in the pattern of a `let` must
/// be given some type, and `()` serves.
pub(super) fn diverges(expr: &EExpr) -> bool {
    let block = |block: &EBlock| {
        block.stmts.iter().any(|stmt| match stmt {
            EStmt::Let { value, .. } | EStmt::Assign { value, .. } | EStmt::Expr(value) => {
                diverges(value)
            }
        }) || block.tail.as_deref().is_some_and(diverges)
    };
    match expr {
        EExpr::Trap
        | EExpr::Panic { .. }
        | EExpr::Break(_)
        | EExpr::Continue
        | EExpr::Return(_) => true,
        EExpr::If {
            then_block,
            else_block,
            ..
        } => block(then_block) && block(else_block),
        EExpr::Match { arms, .. } => arms.iter().all(|arm| block(&arm.body)),
        EExpr::Block(inner) => block(inner),
        EExpr::Loop { body, .. } => {
            // Counting breaks in nested loops is conservative: it may miss
            // a diverging outer loop, but never removes a reachable tail.
            struct Breaks(bool);
            impl Visit for Breaks {
                fn expr(&mut self, expr: &EExpr) {
                    self.0 |= matches!(expr, EExpr::Break(_));
                    cleanup::walk_expr(self, expr);
                }
            }
            let mut breaks = Breaks(false);
            breaks.block(body);
            !breaks.0
        }
        _ => false,
    }
}

/// Whether an expression contains a point that never yields a value, a
/// transfer of control, a trap, or a panic, anywhere inside it. Rust types
/// such a point as `!`, and where it stands in a tuple or an arm the type of
/// the whole may stay undetermined, so a `let` bound to such an expression
/// is given its type. That is the only use of this: annotating too little
/// costs an error from rustc, and annotating too much costs nothing, since
/// every name's type is its own.
fn contains_divergence(expr: &EExpr) -> bool {
    let any = |exprs: &[EExpr]| exprs.iter().any(contains_divergence);
    let block = |block: &EBlock| {
        block.stmts.iter().any(|stmt| match stmt {
            EStmt::Let { value, .. } | EStmt::Assign { value, .. } => contains_divergence(value),
            EStmt::Expr(expr) => contains_divergence(expr),
        }) || block.tail.as_deref().is_some_and(contains_divergence)
    };
    match expr {
        EExpr::Trap
        | EExpr::Panic { .. }
        | EExpr::Break(_)
        | EExpr::Continue
        | EExpr::Return(_) => true,
        EExpr::Var { .. }
        | EExpr::Bool(_)
        | EExpr::Literal(..)
        | EExpr::Proved
        | EExpr::Ghost
        | EExpr::Lend { .. } => false,
        EExpr::Buffer {
            arguments: exprs, ..
        }
        | EExpr::Tuple(exprs)
        | EExpr::Variant { payload: exprs, .. }
        | EExpr::Call {
            arguments: exprs, ..
        } => any(exprs),
        EExpr::Struct { fields, .. } => fields.iter().any(|(_, value)| contains_divergence(value)),
        EExpr::BoxNew(target)
        | EExpr::BoxDeref(target)
        | EExpr::Shared { value: target, .. }
        | EExpr::Deref(target)
        | EExpr::Field { target, .. }
        | EExpr::Cast { expr: target, .. }
        | EExpr::Assert {
            condition: target, ..
        } => contains_divergence(target),
        EExpr::Method {
            receiver,
            arguments,
            ..
        } => contains_divergence(receiver) || any(arguments),
        EExpr::Operate { operands, .. } => any(operands),
        EExpr::Compare { left, right, .. } => {
            contains_divergence(left) || contains_divergence(right)
        }
        EExpr::If {
            condition,
            then_block,
            else_block,
        } => contains_divergence(condition) || block(then_block) || block(else_block),
        EExpr::Match {
            scrutinee, arms, ..
        } => contains_divergence(scrutinee) || arms.iter().any(|arm| block(&arm.body)),
        EExpr::Block(inner) | EExpr::Loop { body: inner, .. } => block(inner),
        EExpr::While { condition, body } => contains_divergence(condition) || block(body),
        EExpr::For { lo, hi, body, .. } => {
            contains_divergence(lo) || contains_divergence(hi) || block(body)
        }
    }
}

/// Rust's precedence of an operator: unary minus binds tightest, then `*`,
/// `/`, and `%`, then `+` and `-`.
fn precedence(op: Op) -> u8 {
    match op {
        Op::Add | Op::Sub => 1,
        Op::Mul | Op::Div | Op::Rem => 2,
        _ => 3,
    }
}

/// A literal with its type as a suffix; a negative one in parentheses, so
/// that a method call or a cast applies to the literal and not to its
/// magnitude.
fn literal(ty: MachineInt, value: i128) -> String {
    if value < 0 {
        format!("({value}_{})", ty.name())
    } else {
        format!("{value}_{}", ty.name())
    }
}

fn pattern_of(pattern: &EPattern) -> String {
    match pattern {
        EPattern::Bind {
            name,
            mutable: true,
            ..
        } => format!("mut {name}"),
        EPattern::Bind { name, .. } => name.clone(),
        EPattern::Wildcard => "_".into(),
        EPattern::Tuple(patterns) => {
            let patterns: Vec<String> = patterns.iter().map(pattern_of).collect();
            tuple_of(&patterns)
        }
    }
}

impl Value {
    /// The value as Rust's `{:?}` would print it, for comparing a compiled
    /// program's output with the interpreter's.
    pub fn debug(&self, module: &Module) -> String {
        let all = |values: &[Value]| -> Vec<String> {
            values.iter().map(|value| value.debug(module)).collect()
        };
        match self {
            Self::Buffer(items) => format!("[{}]", all(items).join(", ")),
            Self::Bool(flag) => flag.to_string(),
            Self::Int(_, value) => value.to_string(),
            Self::Proved | Self::Ghost => "Erased".into(),
            Self::Tuple(fields) => tuple_of(&all(fields)),
            Self::Struct(id, fields) => {
                let Some(item) = module.structs.iter().find(|item| item.id == *id) else {
                    return "UnknownStruct".into();
                };
                let fields: Vec<String> = item
                    .fields
                    .iter()
                    .zip(all(fields))
                    .map(|((name, _), value)| format!("{name}: {value}"))
                    .collect();
                format!("{} {{ {} }}", item.name, fields.join(", "))
            }
            Self::Variant(id, index, payload) => {
                let variant = module
                    .enums
                    .iter()
                    .find(|item| item.id == *id)
                    .and_then(|item| item.variants.get(*index));
                let Some(variant) = variant else {
                    return "UnknownVariant".into();
                };
                variant_of(&variant.name, variant.fields.as_deref(), &all(payload))
            }
        }
    }
}

impl Module {
    /// The field names of a variant written with braces, by the names of
    /// the enum and the variant, which are unique in a module.
    fn variant_fields(&self, enum_name: &str, variant_name: &str) -> Option<&[String]> {
        self.enums
            .iter()
            .find(|item| item.name == enum_name)?
            .variants
            .iter()
            .find(|variant| variant.name == variant_name)?
            .fields
            .as_deref()
    }
}

/// A variant pattern as Rust writes it: `V`, `V(a, _)`, or, for a variant
/// with named fields, `V { a, b: y, .. }`: a field bound to its own name is
/// written once, as Rust's lint asks, and the fields bound to `_` are left
/// to `..`.
fn variant_pattern(name: &str, fields: Option<&[String]>, bound: &[String]) -> String {
    let Some(fields) = fields else {
        return variant_of(name, None, bound);
    };
    let mut written: Vec<String> = Vec::new();
    for (field, name) in fields.iter().zip(bound) {
        if name == "_" {
            continue;
        }
        written.push(if name == field {
            field.clone()
        } else {
            format!("{field}: {name}")
        });
    }
    if written.len() < fields.len() {
        written.push("..".into());
    }
    if written.is_empty() {
        format!("{name} {{}}")
    } else {
        format!("{name} {{ {} }}", written.join(", "))
    }
}

/// A variant with its payload as Rust writes it: `V`, `V(a, b)`, or, for a
/// variant with named fields, `V { a: x, b: y }`, in a declaration, an
/// expression, and a value alike.
fn variant_of(name: &str, fields: Option<&[String]>, payload: &[String]) -> String {
    match fields {
        Some(fields) => {
            let fields: Vec<String> = fields
                .iter()
                .zip(payload)
                .map(|(field, value)| format!("{field}: {value}"))
                .collect();
            format!("{name} {{ {} }}", fields.join(", "))
        }
        None if payload.is_empty() => name.to_string(),
        None => format!("{name}({})", payload.join(", ")),
    }
}

fn lifetime_parameters<'a>(types: impl Iterator<Item = &'a EType>) -> String {
    fn collect(ty: &EType, names: &mut Vec<String>) {
        match ty {
            EType::Ref(lifetime, inner) => {
                if let Some(l) = lifetime
                    && l != "'_"
                    && !names.contains(l)
                {
                    names.push(l.clone());
                }
                collect(inner, names);
            }
            EType::Tuple(fields) => {
                for f in fields {
                    collect(f, names)
                }
            }
            EType::Boxed(t) | EType::Buffer(t) | EType::Array(t, _) | EType::Slice(t) => {
                collect(t, names)
            }
            EType::StructApplied(_, args) | EType::EnumApplied(_, args) => {
                for l in args {
                    if l != "'_" && !names.contains(l) {
                        names.push(l.clone());
                    }
                }
            }
            EType::Fn(args, out) => {
                for a in args {
                    collect(a, names)
                }
                collect(out, names)
            }
            _ => {}
        }
    }
    let mut names = Vec::new();
    for ty in types {
        collect(ty, &mut names)
    }
    if names.is_empty() {
        String::new()
    } else {
        format!("<{}>", names.join(", "))
    }
}
