//! The Rust printer: the erased tree as Rust source. Trusted, together with
//! the Rust toolchain beneath it.
//!
//! The erased tree already has the shape of the source, so this is mostly a
//! matter of spelling. Layout is left to rustfmt. Two constructs have no
//! direct Rust form and are printed through mutable state:
//!
//! ~~~text
//! loop (acc: u8 = 0) -> R { ... continue(next) ... break value ... }
//!
//! {
//!     let mut state_acc: u8 = 0;
//!     loop {
//!         let acc = state_acc;
//!         ... { state_acc = next; continue; } ... break value ...
//!     }
//! }
//! ~~~
//!
//! The state lives in variables of its own and each iteration rebinds the
//! source's names from them, so a `let` in the body that shadows a state
//! name cannot disturb the loop, exactly as in Locus. A `for` is printed the
//! same way around a Rust `for`, and yields its final state.
//!
//! Every value in the core is immutable and freely reusable, so structs and
//! enums derive `Copy`.
//!
//! A panic is printed as `panic!("{}", "message")`. The message is an
//! argument and never the format string, so its braces mean nothing to
//! `panic!`, and it is written as Rust's `{:?}` writes a string, which is a
//! string literal for any text. Whatever follows a panic in evaluation order
//! is still printed, as it is for a trap: the rest of a block, the other
//! arguments of a call, the call itself. Rust warns that such code is
//! unreachable, and the header allows exactly that on purpose, since the
//! printer keeps the shape of the source and does not prune it.

use std::fmt::Write;

use crate::kernel::{Prim, VarId};
use crate::typed::CompareOp;

use super::interp::Value;
use super::tree::{EBlock, EExpr, EPattern, EStmt, EType, Module};

const HEADER: &str = "\
// Generated by Locus. Do not edit.
#![allow(dead_code, unused_variables, unused_parens, unused_braces, unreachable_code)]
#![allow(clippy::all)]

/// The erasure of a proof. It occupies no space.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Proved;

/// The erasure of any other ghost value. It occupies no space.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Ghost;
";

/// The state variables of the loops enclosing the current position.
type Loops = Vec<Vec<String>>;

struct Printer<'m> {
    module: &'m Module,
    out: String,
    loops: Loops,
}

/// The module as Rust source.
pub fn print_module(module: &Module) -> String {
    let mut printer = Printer {
        module,
        out: String::from(HEADER),
        loops: Vec::new(),
    };
    for item in &module.structs {
        let _ = writeln!(
            printer.out,
            "\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub struct {} {{",
            item.name
        );
        for (name, ty) in &item.fields {
            let ty = printer.ty(ty);
            let _ = writeln!(printer.out, "    pub {name}: {ty},");
        }
        printer.out.push_str("}\n");
    }
    for item in &module.enums {
        let _ = writeln!(
            printer.out,
            "\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub enum {} {{",
            item.name
        );
        for variant in &item.variants {
            let payload: Vec<String> = variant.payload.iter().map(|ty| printer.ty(ty)).collect();
            if payload.is_empty() {
                let _ = writeln!(printer.out, "    {},", variant.name);
            } else {
                let _ = writeln!(printer.out, "    {}({}),", variant.name, payload.join(", "));
            }
        }
        printer.out.push_str("}\n");
    }
    for function in &module.fns {
        let params: Vec<String> = function
            .params
            .iter()
            .map(|(_, name, ty)| format!("{name}: {}", printer.ty(ty)))
            .collect();
        let result = printer.ty(&function.result);
        let _ = write!(
            printer.out,
            "\npub fn {}({}) -> {result} ",
            function.name,
            params.join(", ")
        );
        printer.loops.clear();
        let body = printer.block(&function.body);
        printer.out.push_str(&body);
        printer.out.push('\n');
    }
    indent(&printer.out)
}

/// Indents by brace depth. The printer emits one statement per line, and a
/// string literal, which is the message of a panic or of a trap, stays on
/// its line, so counting the braces outside literals is exact.
fn indent(source: &str) -> String {
    let mut out = String::new();
    let mut depth = 0usize;
    for line in source.lines() {
        let line = line.trim();
        let closes_first = line.starts_with('}');
        if closes_first {
            depth = depth.saturating_sub(1);
        }
        if !line.is_empty() {
            out.push_str(&"    ".repeat(depth));
            out.push_str(line);
        }
        out.push('\n');
        let (opens, closes) = braces(line);
        depth = (depth + opens).saturating_sub(closes - usize::from(closes_first));
    }
    out
}

/// The opening and closing braces of a line, outside its string literals.
fn braces(line: &str) -> (usize, usize) {
    let (mut opens, mut closes) = (0, 0);
    let mut in_literal = false;
    let mut chars = line.chars();
    while let Some(c) = chars.next() {
        match c {
            '\\' if in_literal => {
                chars.next();
            }
            '"' => in_literal = !in_literal,
            '{' if !in_literal => opens += 1,
            '}' if !in_literal => closes += 1,
            _ => {}
        }
    }
    (opens, closes)
}

fn tuple_of(items: &[String]) -> String {
    match items {
        [only] => format!("({only},)"),
        _ => format!("({})", items.join(", ")),
    }
}

impl Printer<'_> {
    fn ty(&self, ty: &EType) -> String {
        match ty {
            EType::Bool => "bool".into(),
            EType::U8 => "u8".into(),
            EType::Proved => "Proved".into(),
            EType::Ghost => "Ghost".into(),
            EType::Tuple(fields) => {
                let fields: Vec<String> = fields.iter().map(|field| self.ty(field)).collect();
                tuple_of(&fields)
            }
            EType::Struct(id) => self
                .module
                .structs
                .iter()
                .find(|item| item.id == *id)
                .map_or_else(|| "UnknownStruct".into(), |item| item.name.clone()),
            EType::Enum(id) => self
                .module
                .enums
                .iter()
                .find(|item| item.id == *id)
                .map_or_else(|| "UnknownEnum".into(), |item| item.name.clone()),
            EType::Fn(params, result) => {
                let params: Vec<String> = params.iter().map(|param| self.ty(param)).collect();
                format!("fn({}) -> {}", params.join(", "), self.ty(result))
            }
        }
    }

    fn block(&mut self, block: &EBlock) -> String {
        format!("{{\n{}}}", self.contents(block))
    }

    /// A block's statements and tail, without its braces. A loop, a `for`, a
    /// nested block, or a `continue` in tail position is written straight
    /// into the enclosing block instead of getting braces of its own.
    fn contents(&mut self, block: &EBlock) -> String {
        let mut out = String::new();
        for stmt in &block.stmts {
            match stmt {
                EStmt::Let { pattern, value } => {
                    let value = self.expr(value);
                    let _ = writeln!(out, "let {} = {value};", pattern_of(pattern));
                }
                EStmt::Expr(expr) => {
                    let expr = self.expr(expr);
                    let _ = writeln!(out, "{expr};");
                }
            }
        }
        match block.tail.as_deref() {
            None => {}
            Some(EExpr::Block(inner)) => out.push_str(&self.contents(inner)),
            Some(EExpr::Loop { state, body, .. }) => out.push_str(&self.looping(state, body, None)),
            Some(EExpr::For {
                index,
                lo,
                hi,
                state,
                body,
            }) => {
                let header = format!("for {} in {}..{}", index.1, self.expr(lo), self.expr(hi));
                out.push_str(&self.looping(state, body, Some(header)));
            }
            Some(EExpr::Continue(next)) => out.push_str(&self.continuing(next)),
            Some(tail) => {
                out.push_str(&self.expr(tail));
                out.push('\n');
            }
        }
        out
    }

    /// A loop or a `for` as statements: the state's declarations, the loop,
    /// and for a `for` the final state as the value.
    fn looping(
        &mut self,
        state: &[(VarId, String, EType, EExpr)],
        body: &EBlock,
        for_header: Option<String>,
    ) -> String {
        let (names, declare, rebind) = self.state(state);
        let result = tuple_of(&names);
        self.loops.push(names);
        let body = self.contents(body);
        self.loops.pop();
        match for_header {
            None => format!("{declare}loop {{\n{rebind}{body}}}\n"),
            Some(header) => format!("{declare}{header} {{\n{rebind}{body}}}\n{result}\n"),
        }
    }

    /// `continue(next...)` as statements. The right side is evaluated in
    /// full before any state is assigned.
    fn continuing(&mut self, next: &[EExpr]) -> String {
        let next = self.all(next);
        let slots = self.loops.last().cloned().unwrap_or_default();
        match slots.as_slice() {
            [] => "continue\n".into(),
            [slot] => format!("{slot} = {};\ncontinue\n", next.join(", ")),
            _ => format!("{} = {};\ncontinue\n", tuple_of(&slots), tuple_of(&next)),
        }
    }

    /// A condition, without the parentheses a comparison gets elsewhere.
    fn condition(&mut self, expr: &EExpr) -> String {
        let printed = self.expr(expr);
        match expr {
            EExpr::Compare { .. } => printed[1..printed.len() - 1].to_string(),
            _ => printed,
        }
    }

    fn all(&mut self, exprs: &[EExpr]) -> Vec<String> {
        exprs.iter().map(|expr| self.expr(expr)).collect()
    }

    /// Declares the state variables of a loop and returns their names, the
    /// declarations, and the rebinding of the source's names that starts
    /// each iteration.
    fn state(&mut self, state: &[(VarId, String, EType, EExpr)]) -> (Vec<String>, String, String) {
        let mut names = Vec::new();
        let mut declare = String::new();
        let mut rebind = String::new();
        for (_, name, ty, init) in state {
            let slot = format!("state_{name}");
            let init = self.expr(init);
            let _ = writeln!(declare, "let mut {slot}: {} = {init};", self.ty(ty));
            let _ = writeln!(rebind, "let {name} = {slot};");
            names.push(slot);
        }
        (names, declare, rebind)
    }

    fn expr(&mut self, expr: &EExpr) -> String {
        match expr {
            EExpr::Var { name, .. } => name.clone(),
            EExpr::Bool(value) => value.to_string(),
            EExpr::U8(value) => value.to_string(),
            EExpr::Proved => "Proved".into(),
            EExpr::Ghost => "Ghost".into(),
            EExpr::Trap => "unreachable!(\"shown never to be reached\")".into(),
            EExpr::Panic { message } => format!("panic!(\"{{}}\", {message:?})"),
            EExpr::Tuple(fields) => tuple_of(&self.all(fields)),
            EExpr::Struct { name, fields, .. } => {
                let fields: Vec<String> = fields
                    .iter()
                    .map(|(field, value)| format!("{field}: {}", self.expr(value)))
                    .collect();
                format!("{name} {{ {} }}", fields.join(", "))
            }
            EExpr::Variant {
                enum_name,
                variant_name,
                payload,
                ..
            } => {
                if payload.is_empty() {
                    format!("{enum_name}::{variant_name}")
                } else {
                    format!(
                        "{enum_name}::{variant_name}({})",
                        self.all(payload).join(", ")
                    )
                }
            }
            EExpr::Field {
                target,
                index,
                name,
            } => {
                let target = self.expr(target);
                match name {
                    Some(name) => format!("{target}.{name}"),
                    None => format!("{target}.{index}"),
                }
            }
            EExpr::Method {
                prim,
                receiver,
                arguments,
            } => {
                let method = match prim {
                    Prim::WrappingAdd => "wrapping_add",
                    Prim::WrappingSub => "wrapping_sub",
                    other => other.name(),
                };
                // Rust cannot choose a type for a bare literal receiver.
                let receiver = match &**receiver {
                    EExpr::U8(value) => format!("{value}_u8"),
                    other => self.expr(other),
                };
                format!("{}.{method}({})", receiver, self.all(arguments).join(", "))
            }
            EExpr::Compare { op, left, right } => {
                let op = match op {
                    CompareOp::Eq => "==",
                    CompareOp::Ne => "!=",
                    CompareOp::Lt => "<",
                    CompareOp::Le => "<=",
                    CompareOp::Gt => ">",
                    CompareOp::Ge => ">=",
                };
                format!("({} {op} {})", self.expr(left), self.expr(right))
            }
            EExpr::Call {
                name, arguments, ..
            } => format!("{name}({})", self.all(arguments).join(", ")),
            EExpr::If {
                condition,
                then_block,
                else_block,
            } => format!(
                "if {} {} else {}",
                self.condition(condition),
                self.block(then_block),
                self.block(else_block)
            ),
            EExpr::Match {
                scrutinee,
                enum_name,
                arms,
            } => {
                let mut out = format!("match {} {{\n", self.expr(scrutinee));
                for arm in arms {
                    let payload: Vec<&str> =
                        arm.payload.iter().map(|(_, name)| name.as_str()).collect();
                    let pattern = if payload.is_empty() {
                        format!("{enum_name}::{}", arm.variant_name)
                    } else {
                        format!("{enum_name}::{}({})", arm.variant_name, payload.join(", "))
                    };
                    let body = self.block(&arm.body);
                    let _ = writeln!(out, "{pattern} => {body}");
                }
                out.push('}');
                out
            }
            EExpr::Block(block) => self.block(block),
            // Not in tail position: as a block of its own.
            EExpr::Loop { state, body, .. } => format!("{{\n{}}}", self.looping(state, body, None)),
            EExpr::For {
                index,
                lo,
                hi,
                state,
                body,
            } => {
                let header = format!("for {} in {}..{}", index.1, self.expr(lo), self.expr(hi));
                format!("{{\n{}}}", self.looping(state, body, Some(header)))
            }
            EExpr::Break(value) => format!("break {}", self.expr(value)),
            EExpr::Continue(next) => format!("{{\n{}}}", self.continuing(next)),
        }
    }
}

fn pattern_of(pattern: &EPattern) -> String {
    match pattern {
        EPattern::Bind { name, .. } => name.clone(),
        EPattern::Wildcard => "_".into(),
        EPattern::Tuple(patterns) => {
            let patterns: Vec<String> = patterns.iter().map(pattern_of).collect();
            tuple_of(&patterns)
        }
    }
}

impl Value {
    /// The value as Rust's `{:?}` would print it, for comparing a compiled
    /// program's output with the interpreter's.
    pub fn debug(&self, module: &Module) -> String {
        let all = |values: &[Value]| -> Vec<String> {
            values.iter().map(|value| value.debug(module)).collect()
        };
        match self {
            Self::Bool(flag) => flag.to_string(),
            Self::U8(byte) => byte.to_string(),
            Self::Proved => "Proved".into(),
            Self::Ghost => "Ghost".into(),
            Self::Tuple(fields) => tuple_of(&all(fields)),
            Self::Struct(id, fields) => {
                let Some(item) = module.structs.iter().find(|item| item.id == *id) else {
                    return "UnknownStruct".into();
                };
                let fields: Vec<String> = item
                    .fields
                    .iter()
                    .zip(all(fields))
                    .map(|((name, _), value)| format!("{name}: {value}"))
                    .collect();
                format!("{} {{ {} }}", item.name, fields.join(", "))
            }
            Self::Variant(id, index, payload) => {
                let name = module
                    .enums
                    .iter()
                    .find(|item| item.id == *id)
                    .and_then(|item| item.variants.get(*index))
                    .map_or("UnknownVariant", |variant| variant.name.as_str());
                if payload.is_empty() {
                    name.to_string()
                } else {
                    format!("{name}({})", all(payload).join(", "))
                }
            }
        }
    }
}
