#!/usr/bin/env python3
"""Writes tests/corpus/accept/casts.lc: `as` between every pair of machine
integer types at a boundary set of the source type, with the result of each
call as Rust computes it. The corpus runner runs every line in both
interpreters and compares them with the compiled Rust, so the file is what
ties the kernel's `cast` to Rust's `as`.

    python3 tools/casts.py > tests/corpus/accept/casts.lc
"""

TYPES = {
    "u8": (0, 2**8 - 1),
    "u16": (0, 2**16 - 1),
    "u32": (0, 2**32 - 1),
    "u64": (0, 2**64 - 1),
    "i8": (-(2**7), 2**7 - 1),
    "i16": (-(2**15), 2**15 - 1),
    "i32": (-(2**31), 2**31 - 1),
    "i64": (-(2**63), 2**63 - 1),
}


def boundary(ty):
    """The ends of the range and their neighbours, zero and its neighbours,
    and the middle of the range, each within the range, in order."""
    low, high = TYPES[ty]
    half = (high + 1) // 2
    values = [low, low + 1, -1, 0, 1, half - 1, half, high - 1, high]
    seen = []
    for value in values:
        if low <= value <= high and value not in seen:
            seen.append(value)
    return seen


def wrap(ty, value):
    """Rust's `as` into `ty`: reduction modulo 2^bits into the range."""
    low, high = TYPES[ty]
    modulus = high - low + 1
    reduced = value % modulus
    if reduced > high:
        reduced -= modulus
    return reduced


def literal(ty, value):
    return f"-{-value}" if value < 0 else str(value)


def main():
    print("// `as` between every pair of machine integer types, at a boundary set of")
    print("// the source type. Generated by tools/casts.py; each expected result is")
    print("// what Rust computes, and the corpus runner compares the compiled Rust")
    print("// with both interpreters.")
    print()
    for source in TYPES:
        for target in TYPES:
            print(f"fn {source}_to_{target}(x: {source}) -> {target} {{ x as {target} }}")
    print()
    for source in TYPES:
        for target in TYPES:
            for value in boundary(source):
                result = wrap(target, value)
                print(
                    f"//~ run: {source}_to_{target}({literal(source, value)}) => {literal(target, result)}"
                )


if __name__ == "__main__":
    main()
