#!/usr/bin/env python3
"""Writes tests/corpus/accept/operators.lc: the operators `+ - * / %` and
unary minus at u8, i8, u32, and i64, applied to a boundary set of each
type crossed with itself, with the outcome Rust computes in each build.

A run line with one outcome holds in both builds; one with two, `=> panic
| 0`, gives the outcome with overflow checks on and then with them off.
The corpus runner compares both interpreters in both modes and the Rust
compiled both ways with these lines, so the file is the table of
src/kernel/ops.rs checked against rustc at the boundary.

    python3 tools/operators.py > tests/corpus/accept/operators.lc
"""

TYPES = {
    "u8": (0, 255, [0, 1, 127, 128, 255]),
    "i8": (-128, 127, [-128, -127, -1, 0, 1, 127]),
    "u32": (0, 4294967295, [0, 1, 2, 4294967295]),
    "i64": (-(2**63), 2**63 - 1, [-(2**63), -1, 0, 1, 2**63 - 1]),
}

OPS = [
    ("add", "+"),
    ("sub", "-"),
    ("mul", "*"),
    ("div", "/"),
    ("rem", "%"),
]

MESSAGES = {
    "add": "attempt to add with overflow",
    "sub": "attempt to subtract with overflow",
    "mul": "attempt to multiply with overflow",
    "neg": "attempt to negate with overflow",
}


def wrap(value, lo, hi):
    width = hi - lo + 1
    return (value - lo) % width + lo


def exact(op, a, b):
    if op == "add":
        return a + b
    if op == "sub":
        return a - b
    if op == "mul":
        return a * b
    if op == "neg":
        return -a
    # Truncating division and its remainder, as Rust and the kernel define them.
    quotient = abs(a) // abs(b)
    if (a < 0) != (b < 0):
        quotient = -quotient
    if op == "div":
        return quotient
    return a - quotient * b


def outcome(op, ty, a, b):
    """The run line's expectation: one outcome, or checked | wrapping."""
    lo, hi, _ = TYPES[ty]
    signed = lo < 0
    if op in ("div", "rem"):
        if b == 0:
            what = "divide by zero" if op == "div" else "calculate the remainder with a divisor of zero"
            return f"panic: attempt to {what}"
        if signed and a == lo and b == -1:
            what = "divide with overflow" if op == "div" else "calculate the remainder with overflow"
            return f"panic: attempt to {what}"
        return str(exact(op, a, b))
    value = exact(op, a, b)
    if lo <= value <= hi:
        return str(value)
    return f"panic: {MESSAGES[op]} | {wrap(value, lo, hi)}"


def main():
    print("// The operators at a boundary set of u8, i8, u32, and i64, each with")
    print("// the outcome Rust computes: one outcome holds in both builds; `=> panic")
    print("// | value` is the outcome with overflow checks on, then with them off.")
    print("// Generated by tools/operators.py; the corpus runner compares both")
    print("// interpreters in both modes and the Rust compiled both ways with it.")
    print()
    runs = []
    for ty, (lo, hi, values) in TYPES.items():
        for op, symbol in OPS:
            print(f"fn {op}_{ty}(a: {ty}, b: {ty}) -> {ty} {{ a {symbol} b }}")
            for a in values:
                for b in values:
                    runs.append(f"//~ run: {op}_{ty}({a}, {b}) => {outcome(op, ty, a, b)}")
        if lo < 0:
            print(f"fn neg_{ty}(a: {ty}) -> {ty} {{ -a }}")
            for a in values:
                runs.append(f"//~ run: neg_{ty}({a}) => {outcome('neg', ty, a, 0)}")
    print()
    print("\n".join(runs))


if __name__ == "__main__":
    main()
