//! `locus build`: the checked files as a Rust crate on disk (Target
//! language: What is generated; LOC-135).
//!
//! The layout is the plain Cargo one, so that nothing has to be explained
//! to a Rust reader: `Cargo.toml`, `src/lib.rs`, and one `src/<name>.rs` for
//! each Locus file, named after the file. The root, `src/lib.rs`, holds the
//! marker types and their private constructors, and a `pub mod` line for
//! each module, so that every module sees the same `Erased` marker and evidence
//! returned by one file can be taken by another; each module imports the
//! markers from the root instead of defining its own. The markers are
//! private to make where it counts: a module under the root can name a
//! marker's constructor, since Rust lets a module use what is private to
//! its ancestors, and a crate that depends on the generated one cannot.
//!
//! What is written is a function of the files alone: the modules are in the
//! order of their names, and a second run writes the same bytes.

use std::io;
use std::path::{Path, PathBuf};

use crate::erased::print_root_for_modules;
use crate::lexer::{self, TokenKind};
use crate::source::SourceMap;

/// The name of the module a file becomes: its stem, which is what Rust
/// names a file module by. It must be an identifier that is no keyword,
/// which the lexer decides, in lower case, since Rust warns of a module
/// named otherwise, and not `lib`, which is the root.
pub fn module_name(path: &Path) -> Result<String, String> {
    let shown = path.display();
    let Some(stem) = path.file_stem().and_then(|stem| stem.to_str()) else {
        return Err(format!("`{shown}` has no name to make a module of"));
    };
    let stem = stem.to_string();
    let mut sources = SourceMap::default();
    let file = sources.add("module name", stem.clone());
    let lexed = lexer::lex(sources.get(file));
    let is_identifier = lexed.diagnostics.is_empty()
        && lexed.tokens.len() == 2
        && lexed.tokens[0].kind == TokenKind::Name
        && stem.chars().all(|c| !c.is_ascii_uppercase());
    if !is_identifier || stem == "lib" {
        return Err(format!(
            "`{shown}` would be the module `{stem}`, and a module's name is a lower-case identifier that is no keyword, and not `lib`, which is the root"
        ));
    }
    Ok(stem)
}

/// The crate's name when `--name` does not give one: the directory's.
pub fn crate_name_of(directory: &Path) -> Result<String, String> {
    match directory.file_name().and_then(|name| name.to_str()) {
        Some(name) if !name.is_empty() && name != "." && name != ".." => Ok(name.to_string()),
        _ => Err(format!(
            "`{}` gives the crate no name; say `--name <crate>`",
            directory.display()
        )),
    }
}

/// The manifest: a name and an edition, and no dependencies, since the
/// generated code has none.
pub fn cargo_toml(name: &str) -> String {
    format!(
        "# Generated by Locus. Do not edit.\n[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[dependencies]\n"
    )
}

/// Writes the crate under `directory`, creating it as needed: the manifest,
/// the root, and each module, whose Rust is as `print_module_with` printed
/// it with the markers in the root. Returns the paths written, in order.
pub fn write_crate(
    directory: &Path,
    name: &str,
    modules: &[(String, String)],
) -> io::Result<Vec<PathBuf>> {
    let mut modules: Vec<&(String, String)> = modules.iter().collect();
    modules.sort_by(|a, b| a.0.cmp(&b.0));
    let source = directory.join("src");
    std::fs::create_dir_all(&source)?;
    let mut written = Vec::new();
    let manifest = directory.join("Cargo.toml");
    std::fs::write(&manifest, cargo_toml(name))?;
    written.push(manifest);
    let root = source.join("lib.rs");
    std::fs::write(
        &root,
        print_root_for_modules(
            &modules
                .iter()
                .map(|module| (*module).clone())
                .collect::<Vec<_>>(),
        ),
    )?;
    written.push(root);
    for (module, rust) in modules {
        let path = source.join(format!("{module}.rs"));
        std::fs::write(&path, rust)?;
        written.push(path);
    }
    Ok(written)
}
